NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Organization Name"
ORG_DBA="Organization DBA"
ORG_URL="https://algoshitcoin.github.io"
ORG_LOGO="https://algoshitcoin.github.io/logo.png"

[[PRINCIPALS]]
name="Eric Shitman"
email="eric@shitman.com"

[[CURRENCIES]]
code="aSHT"
issuer=""
display_decimals=2
name="SHIT Coin"
desc="aSHT is a Shitty stablecoin pegged 1:1 to other SHITS. It's designed to stay exactly the same — block after block — while everything else goes to shit."
conditions="There will only ever be 51.000.000 aSHT tokens in existence."
image="https://algoshitcoin.github.io/logo.png"
fixed_number=51000000
